name: freshcut_challenge
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^1.0.4
  riverpod: ^1.0.3

  # UI
  percent_indicator: ^4.2.2
  gradient_borders: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AktivGrotesk
      fonts:
        - asset: assets/fonts/100_AktivGrotesk_Trial_Hair.ttf
          weight: 100
        - asset: assets/fonts/200_AktivGrotesk_Trial_Th.ttf
          weight: 200
        - asset: assets/fonts/300_AktivGrotesk_Trial_Lt.ttf
          weight: 300
        - asset: assets/fonts/400_AktivGrotesk_Trial_Rg.ttf
          weight: 400
        - asset: assets/fonts/500_AktivGrotesk_Trial_Md.ttf
          weight: 500
        - asset: assets/fonts/600_AktivGrotesk_Trial_SBd.ttf
          weight: 600
        - asset: assets/fonts/700_AktivGrotesk_Trial_Bd.ttf
          weight: 700
        - asset: assets/fonts/800_AktivGrotesk_Trial_XBd.ttf
          weight: 800
        - asset: assets/fonts/900_AktivGrotesk_Trial_Blk.ttf
          weight: 900
        
